apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  # image: otel/opentelemetry-collector-contrib:latest
  image: otel/opentelemetry-collector-contrib:latest 
  config: |
    receivers:
      zipkin:
        endpoint: "0.0.0.0:9411"
    exporters:
      alibabacloud_logservice/sls-trace:
        endpoint: "cn-hangzhou-intranet.log.aliyuncs.com"   
        project: "ngiq-cn-pnt-log"               
        logstore: "ngiq-cn-pnt-trace-traces"              
        access_key_id: "xxxx"
        access_key_secret: "xxxx"
    service:
      pipelines:
        traces:
          receivers: [zipkin]
          exporters: [alibabacloud_logservice/sls-trace]