apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: ngiq-instrumentation
spec:
  exporter:
    endpoint: http://otel-collector:9411
  propagators:
    - tracecontext
    - baggage
    - b3
  # java:
  #   image: ngiq-registry.cn-hangzhou.cr.aliyuncs.com/ngiq-cr/autoinstrumentation-java:latest
  nodejs:
    image: ngiq-registry.cn-hangzhou.cr.aliyuncs.com/ngiq-cr/autoinstrumentation-nodejs:latest
  # python:
  #   image: ngiq-registry.cn-hangzhou.cr.aliyuncs.com/ngiq-cr/autoinstrumentation-python:latest